# SPDX-License-Identifier: Apache-2.0

name: Spellcheck

on:
  pull_request:
    branches:
      - main
      - "release-**"
    paths:
      - '**.md'
      - 'tox.ini'
      - '.spellcheck*'
      - '.github/workflows/spellcheck.yaml' # This workflow file

env:
  LC_ALL: en_US.UTF-8

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  spellcheck:
    name: Spellcheck (en_US)
    runs-on: ubuntu-latest
    steps:
      - name: "Harden Runner"
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6 # v2.8.1
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Checkout Code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Install aspell
        run: |
          sudo sudo apt-get update
          sudo apt-get install -y aspell aspell-en

      - name: Setup Python 3.11
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: 3.11
          cache: pip
          cache-dependency-path: |
            **/pyproject.toml
            **/requirements*.txt

      - name: Install tox dependencies
        run: python -m pip install --upgrade tox

      - name: Run spellchecker
        run: python -m tox -e spellcheck
